sudo: required
services:
  - docker

before_install:
  - docker build -t futumans/docker-react1 -f Dockerfile.dev .

script:
  - docker run -e CI=true futumans/docker-react1 npm run test -- --coverage

language: minimal

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react1" 
  env: "Dockerreact1-env"
  bucket_name: "elasticbeanstalk-us-east-1-652213986584"
  bucket_path: "docker-react1"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
  edge: true